# This file contains values from Cookiecutter

default_context:
  project_name: "storytime"
  project_description: "Storytime is an experiment in continuous storytelling."
  organization: "myrontuttle"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "myrontuttle"
  email: "myrongt@gmail.com"
  version: "0.1.0"
  line_length: "79"
  create_example_template: "none"
